### ISSUE TITLE
ndk-build or CMake port

### ISSUE THREAD

**Issue by rishavambasta** [tinntt/android-system-record-track#2]
Could you port the project to the ndk-build or preferably CMake build system, so that It's easy to build it on recent versions of Android Studio.

**Comment by AndroidDeveloperLB** [comment]
Did you solve it?
For some reason, I've made it through to build the project (using [this link](https://stackoverflow.com/a/40400058/878126)) , but at runtime it crashes with this error:

2018-06-27 09:47:03.505 31614-31614/com.tinntt.myrecorder E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tinntt.myrecorder, PID: 31614
    java.lang.UnsatisfiedLinkError: No implementation found for boolean com.tinntt.myrecorder.MyAudioTrack.nativeInit() (tried Java_com_tinntt_myrecorder_MyAudioTrack_nativeInit and Java_com_tinntt_myrecorder_MyAudioTrack_nativeInit__)
        at com.tinntt.myrecorder.MyAudioTrack.nativeInit(Native Method)
        at com.tinntt.myrecorder.MyAudioTrack.getMinFrame(MyAudioTrack.java:24)
        at com.tinntt.myrecorder.MainActivity.Init(MainActivity.java:91)
        at com.tinntt.myrecorder.MainActivity.access$000(MainActivity.java:27)
        at com.tinntt.myrecorder.MainActivity$1.onClick(MainActivity.java:49)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25883)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Attached the project here.
[android-system-record-track1.zip](https://github.com/tinntt/android-system-record-track/files/2140053/android-system-record-track1.zip)

**Comment by ibtisamasif** [comment]
> Did you solve it?
> For some reason, I've made it through to build the project (using [this link](https://stackoverflow.com/a/40400058/878126)) , but at runtime it crashes with this error:
> 
> 2018-06-27 09:47:03.505 31614-31614/com.tinntt.myrecorder E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.tinntt.myrecorder, PID: 31614
> java.lang.UnsatisfiedLinkError: No implementation found for boolean com.tinntt.myrecorder.MyAudioTrack.nativeInit() (tried Java_com_tinntt_myrecorder_MyAudioTrack_nativeInit and Java_com_tinntt_myrecorder_MyAudioTrack_nativeInit__)
> at com.tinntt.myrecorder.MyAudioTrack.nativeInit(Native Method)
> at com.tinntt.myrecorder.MyAudioTrack.getMinFrame(MyAudioTrack.java:24)
> at com.tinntt.myrecorder.MainActivity.Init(MainActivity.java:91)
> at com.tinntt.myrecorder.MainActivity.access$000(MainActivity.java:27)
> at com.tinntt.myrecorder.MainActivity$1.onClick(MainActivity.java:49)
> at android.view.View.performClick(View.java:6597)
> at android.view.View.performClickInternal(View.java:6574)
> at android.view.View.access$3100(View.java:778)
> at android.view.View$PerformClick.run(View.java:25883)
> at android.os.Handler.handleCallback(Handler.java:873)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:193)
> at android.app.ActivityThread.main(ActivityThread.java:6642)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 
> Attached the project here.
> [android-system-record-track1.zip](https://github.com/tinntt/android-system-record-track/files/2140053/android-system-record-track1.zip)

i am in the same boat. Did you manage to resolve ? getting same error.
